### ISSUE TITLE
请教下拖拽渲染延迟问题

### ISSUE THREAD

**Issue by xmasong** [woai3c/visual-drag-demo#105]
大佬你好，我参考你的文档实现demo到“组件拖拽”功能时，发现我拖动组件后存在延迟，效果如下：
![delay](https://user-images.githubusercontent.com/22997127/210768422-d73ebe33-6548-4d8f-98a6-22f90aa0b50c.gif)

经过初步定位，是因为拖动事件高频触发，但vue的渲染事件会在nextTick中做队列缓存优化，触发频率低于mousemove事件，解决方案是给组件元素加一个动态的key，key随着mousemove变化。

我的demo地址是：https://github.com/xmasong/visual-drag-next 可以复现，我使用了vue3+pinia技术栈实现的这个demo，但是我用vue2+vuex也实现了一版发现也会有延迟问题，已经初步排除了这个差异的影响。

我的疑问是为啥你的项目中看起来没有做这个优化，也没有拖拽延迟，求解答~

**Comment by xmasong** [comment]
@woai3c 没有打开控制台，这个不是控制台卡顿，是属性更新延迟。补充一个信息，我把更新style的方法（getShapeStyle）放在了<component>自定义组件上导致了这个问题，换到<Shape>组件上确实就没有延迟了，但是具体原因未知

**Comment by xmasong** [comment]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/22997127/210923422-6a2d843c-9c77-4beb-9e1b-45de5b353a2a.png">

尝试了图中4种情况，test-1,2是没有拖拽 延迟的，test-3,4是有的，很疑惑，找不到根因

**Comment by xmasong** [comment]
@woai3c 定位到问题了，有延迟的共同点是卡的组件都有`transition:0.1s`这个属性，left/top属性也被all包含，所以都会因为transition有0.1s的延迟，`Shape`组件没有设置这个属性就不会有问题 。再次感谢~

**Comment by woai3c** [comment]
> @woai3c 定位到问题了，有延迟的共同点是卡的组件都有`transition:0.1s`这个属性，left/top属性也被all包含，所以都会因为transition有0.1s的延迟，`Shape`组件没有设置这个属性就不会有问题 。再次感谢~

确实不容易，这个 bug 不容易发现。
