### ISSUE TITLE
所有组件无法拖动，被限制在了一个组件里面

### ISSUE THREAD

**Issue by lp-prog** [woai3c/visual-drag-demo#112]
![image](https://user-images.githubusercontent.com/122333214/233026559-a76d44b4-8fcc-4f1f-94f7-00cfd90ccb83.png)
组件拖动一下会挤在一起，然后无法拖动，请问下大佬，这个是什么问题呢

**Comment by lp-prog** [comment]
像是被限制在了一个容器里

**Comment by lp-prog** [comment]
@woai3c 

https://user-images.githubusercontent.com/122333214/233029944-9c99b4b2-e02b-42e0-a6f8-e97eda9fa56e.mp4

大佬，就是这个效果

**Comment by woai3c** [comment]
> @woai3c
> 
>  Video_2023-04-19_171935.mp4 
> 大佬，就是这个效果

有没有可复现的步骤，你把轮播图去了试试能复现不。感觉跟你的轮播图有关。

**Comment by lp-prog** [comment]
好的，我试试

**Comment by lp-prog** [comment]
好的，我试试 @woai3c

**Comment by lp-prog** [comment]
![image](https://user-images.githubusercontent.com/122333214/233250435-059855f1-bf39-4caf-8649-bda31d1625aa.png)
大佬，我发现这里有时候拿到的是 undefined  这个是为什么，会是问题所在嘛 @woai3c

**Comment by zkjDream** [comment]
插眼，蹲个交流群

**Comment by woai3c** [comment]
> 插眼，蹲个交流群

974534686

**Comment by woai3c** [comment]
> ![image](https://user-images.githubusercontent.com/122333214/233250435-059855f1-bf39-4caf-8649-bda31d1625aa.png) 大佬，我发现这里有时候拿到的是 undefined 这个是为什么，会是问题所在嘛 @woai3c

这是标线对齐用的，能不能提供一下可供复现的最小项目源码。

**Comment by woai3c** [comment]
> MarkLin.vue 里面 eventBus.$on() 里面的 showLine 方法 获取到的 this.$refs 为空 ， 我把eventBus 换成 this 就能拿到相关 refs 了

非常棒。
