### ISSUE TITLE
低代码平台怎么解决组件过多问题，能否做到按需发布，并边运行边修改组件？

### ISSUE THREAD

**Issue by bakewell0** [woai3c/visual-drag-demo#114]

**Comment by woai3c** [comment]
你可以把组件库的每一个组件都做成 NPM 包，按需发布。边运行边修改组件是什么意思？

**Comment by bakewell0** [comment]
我指的是画布上页面做好后，也保存了，发布的页面，是否可以不依赖于平台，独立部署？这个时候生成页面，不应该打包全部组件库。

**Comment by woai3c** [comment]
可以实现的，渲染器是可以分离出来独立部署的。生成的产物是个 JSON,可以分析 JSON，找到它依赖的组件，然后再加载相应的组件即可。不过需要你自己写程序实现这些逻辑。
