### ISSUE TITLE
项目启动不起来，请教下大佬有什么好的排查思路嘛

### ISSUE THREAD

**Issue by jinxudong996** [woai3c/visual-drag-demo#115]
大佬好，当前node环境切换了好几个都是这样，启动不起来，截图如下

![0DF6F7EB-2F06-4c89-A057-0A095533F1C1](https://github.com/woai3c/visual-drag-demo/assets/77560763/11184e55-e9c0-42a6-8c48-51656066730b)
期望得到大佬的解答

**Comment by woai3c** [comment]
用 nodejs16 试试

**Comment by jinxudong996** [comment]
感谢大佬回复，我node切换了三个16的版本， 
    16.17.0
  * 16.16.0 (Currently using 64-bit executable)
    16.15.0
都不行，清除了npm缓存也一样，主要的疑惑点在于我笔记本可以启动的，笔记本node版本还是18的，就是台式机启动不起来，稀奇古怪的问题。。。

**Comment by woai3c** [comment]
网上搜搜吧，这是项目的依赖报错了，信息也很详细。网上应该有解决方案。

**Comment by jinxudong996** [comment]
devserver中的open设置为false就行了。感谢大佬开源的项目

**Comment by woai3c** [comment]
> devserver中的换个端口（别是默认的8080），open设置为false就行了。 我本地又查了下没得程序占用这个端口，莫名其妙的。 感谢大佬开源的项目。

不客气
