### ISSUE TITLE
拖拽中-left，top不能为0，只能是1或者-1

### ISSUE THREAD

**Issue by lvpangpang** [woai3c/visual-drag-demo#118]
阅读源码后发现是setShapeStyle方法中 判断赋值有问题
if (top) curComponent.style.top = Math.round(top)
改成
if (top !== undefined) curComponent.style.top = Math.round(top)
就好了

**Comment by woai3c** [comment]
感谢，方便提个 MR 吗？

**Comment by lvpangpang** [comment]
> 感谢，方便提个 MR 吗？

已发

**Comment by woai3c** [comment]
https://github.com/woai3c/visual-drag-demo/pull/119
