### ISSUE TITLE
事件点击删除后页面上未移除

### ISSUE THREAD

**Issue by wyf521-sudo** [woai3c/visual-drag-demo#12]
![image](https://user-images.githubusercontent.com/64625772/112450082-f62dc800-8d8e-11eb-8f5e-5efc2f65a5eb.png)
（虽然vuex中已经不存在了）

**Comment by woai3c** [comment]
好的，感谢反馈。等过几天有空了就修复。

**Comment by woai3c** [comment]
> ![image](https://user-images.githubusercontent.com/64625772/112450082-f62dc800-8d8e-11eb-8f5e-5efc2f65a5eb.png)
> （虽然vuex中已经不存在了）

已修复，感谢你的反馈。

**Comment by wyf521-sudo** [comment]
![image](https://user-images.githubusercontent.com/64625772/112804093-909b4d80-90a6-11eb-91fd-fed01cfc43d3.png)
可能我说的不是很清楚，就是组件上添加事件，点击事件上的删除按钮后，该事件还存在于页面上

**Comment by woai3c** [comment]
> ![image](https://user-images.githubusercontent.com/64625772/112804093-909b4d80-90a6-11eb-91fd-fed01cfc43d3.png)
> 可能我说的不是很清楚，就是组件上添加事件，点击事件上的删除按钮后，该事件还存在于页面上

好的，过几天有空看一下。

**Comment by woai3c** [comment]
> ![image](https://user-images.githubusercontent.com/64625772/112804093-909b4d80-90a6-11eb-91fd-fed01cfc43d3.png)
> 可能我说的不是很清楚，就是组件上添加事件，点击事件上的删除按钮后，该事件还存在于页面上

已经修复。
