### ISSUE TITLE
多个组件组合后事件不起作用

### ISSUE THREAD

**Issue by JohnChancfz** [woai3c/visual-drag-demo#121]
组件A 添加事件alert('aaa')
组件B 添加事件 alert('bbb')
组合之后 点击组件A /组件B 都不起作用

谢谢

**Comment by woai3c** [comment]
组合后就是一个新组件了 原来的 A B 组件事件是不生效的 无法触发

**Comment by woai3c** [comment]
太久没响应，关闭问题。
