### ISSUE TITLE
导出的默认组件数据，需要深拷贝切断引用关联，不然 撤销有问题

### ISSUE THREAD

**Issue by yzz2333** [woai3c/visual-drag-demo#124]
src\store\snapshot.js 
export function getDefaultcomponentData() {
    return JSON.parse(JSON.stringify(defaultcomponentData))
}
导出的默认组件数据，需要深拷贝切断引用关联，不然 撤销有问题

**Comment by woai3c** [comment]
感谢反馈，已修复。
