### ISSUE TITLE
轮主可以考虑下建议啊

### ISSUE THREAD

**Issue by tongjiaqi** [woai3c/visual-drag-demo#13]
功能很全面了，赞！，更新的也很及时啊，大赞！

框选多个组建后，还需要组合才能一起移动，太麻烦了，可以考虑一下框选后组件们一起动吗？

组件成组后，来个组内移动的小功能会更赞啊，在没有拆分组的情况下可以组内元素进行位移，这样在页面结构复杂的时候混很方便，不用在拆分重组，元素过多的时候或拥挤的时候，框选并不舒适哦。

最后再来个鸟瞰图就更棒了，在画布大小过大的时候(1920x1200)情况下，是看不全页面的，有了鸟瞰图方便太多了！

**Comment by tongjiaqi** [comment]
如果两个组件叠在一起，无法触发框选效果

**Comment by tongjiaqi** [comment]
强烈建议轮主，将轮子插件化，立版本，搞分支，千万别过于臃肿，保留纯粹的拖拉拽功能。

与其做数据交互，不如搞个鸟瞰图、图层、导入导出，来的实在，而且图层功能，实用又强大，在图层上还能合组、上移、锁定、拖拽排序啊等等。

**Comment by tongjiaqi** [comment]
我之前一直在用jqueryui的拖拉拽，轮主可以借鉴下它的拖拉拽核心功能。它主要分为放置、移动、缩放。其中移动里包含了很多小功能，比如限制移动x，y，限制移动范围(不超出父容器)，拖拽助手(元素只能通过助手才能移动)，自由滚屏等等。缩放组件还有保留长宽比例缩放。等等有太多搞头了，而且都是关于拖拉拽的。这里面还有很多啊，轮主别迷茫了

**Comment by woai3c** [comment]
> 我之前一直在用jqueryui的拖拉拽，轮主可以借鉴下它的拖拉拽核心功能。它主要分为放置、移动、缩放。其中移动里包含了很多小功能，比如限制移动x，y，限制移动范围(不超出父容器)，拖拽助手(元素只能通过助手才能移动)，自由滚屏等等。缩放组件还有保留长宽比例缩放。等等有太多搞头了，而且都是关于拖拉拽的。这里面还有很多啊，轮主别迷茫了

我做这个没想着做这么复杂的功能，主要是研究一下拖拽生成页面。

**Comment by tongjiaqi** [comment]
> > 我之前一直在用jqueryui的拖拉拽，轮主可以借鉴下它的拖拉拽核心功能。它主要分为放置、移动、缩放。其中移动里包含了很多小功能，比如限制移动x，y，限制移动范围(不超出父容器)，拖拽助手(元素只能通过助手才能移动)，自由滚屏等等。缩放组件还有保留长宽比例缩放。等等有太多搞头了，而且都是关于拖拉拽的。这里面还有很多啊，轮主别迷茫了
> 
> 我做这个没想着做这么复杂的功能，主要是研究一下拖拽生成页面。

如果这样的话，也可以参考下[vuegg](https://github.com/vuegg/vuegg)，为了方便查阅，我做了简化[vuegg_lite](https://github.com/tongjiaqi/vuegg_lite)，已经很棒了，不过前面提的那几个点可以考虑考虑啊。

**Comment by woai3c** [comment]
> > > 我之前一直在用jqueryui的拖拉拽，轮主可以借鉴下它的拖拉拽核心功能。它主要分为放置、移动、缩放。其中移动里包含了很多小功能，比如限制移动x，y，限制移动范围(不超出父容器)，拖拽助手(元素只能通过助手才能移动)，自由滚屏等等。缩放组件还有保留长宽比例缩放。等等有太多搞头了，而且都是关于拖拉拽的。这里面还有很多啊，轮主别迷茫了
> > 
> > 
> > 我做这个没想着做这么复杂的功能，主要是研究一下拖拽生成页面。
> 
> 如果这样的话，也可以参考下[vuegg](https://github.com/vuegg/vuegg)，为了方便查阅，我做了简化[vuegg_lite](https://github.com/tongjiaqi/vuegg_lite)，已经很棒了，不过前面提的那几个点可以考虑考虑啊。

谢谢你的建议，换新工作了。最近太忙，以后有时间再考虑。
