### ISSUE TITLE
editor容器设置scale伸缩后，组件拖拉与拖动宽高设置有问题

### ISSUE THREAD

**Issue by ahuan0317** [woai3c/visual-drag-demo#130]
这个有办法解决吗，如果不用scale进行伸缩，虽然组件根据比例重新计算了容器宽高，但是组件内部的元素有什么办法也根据比例进行重新计算，有什么思路吗？

**Comment by woai3c** [comment]
目前没想到什么好办法，暂时没思路。如果你后面有好的办法，欢迎提 PR。
