### ISSUE TITLE
你好，我把你的visual-drag-demo项目，翻译成react版本了

### ISSUE THREAD

**Issue by wycJason** [woai3c/visual-drag-demo#131]
你好，我把你的visual-drag-demo项目，翻译成react版本了，如有僭越之处，还请海涵，有任何问题可随时联系我删除！
项目地址：https://github.com/wycJason/visual-drag-demo-react-

**Comment by woai3c** [comment]
非常棒，这是一个非常好的学习方法，加油！

**Comment by wycJason** [comment]
谢谢，有不妥之处，还请指正，必当虚心接受，潜心改正。 

 

 




 
 
  
 
  ----- 原始邮件 -----
  
***@***.***>
  
***@***.***>等3人
  
主题：Re:_[woai3c/visual-drag-demo]_你好，我把你的visual-drag-demo项目，翻译成react版本了_(Issue_#131)
  
日期：2024年03月11日 20:44:06
  

 
 
 
  
 非常棒，这是一个非常好的学习方法，加油！
