### ISSUE TITLE
 收缩右边属性编辑栏会出现报错

### ISSUE THREAD

**Issue by issueye** [woai3c/visual-drag-demo#134]
在选中了组件之后
![image](https://github.com/woai3c/visual-drag-demo/assets/28434476/523011e1-29e4-4797-b16c-6e0765cc631b)

收缩右边属性编辑栏会出现报错
![image](https://github.com/woai3c/visual-drag-demo/assets/28434476/69e2085f-53d0-4940-a9aa-14de3da558cd)

**Comment by woai3c** [comment]
我试了一下没有这个报错，能否说一下详细的复现步骤。

**Comment by woai3c** [comment]
太久没响应，关闭问题。
