### ISSUE TITLE
在中间选中组件之后，然后收缩右边属性栏会出现报错

### ISSUE THREAD

**Issue by issueye** [woai3c/visual-drag-demo#135]
https://github.com/woai3c/visual-drag-demo/assets/28434476/f923a9d2-4092-4729-8c14-88ef168c506d

**Comment by woai3c** [comment]
是否有修改过源码？我按你的步骤没复现出来。

**Comment by issueye** [comment]
emmm... 那就很奇怪了呢   我是拉取的 main 分支的代码直接跑的，我在两台电脑上试过都出现了这样的情况

**Comment by issueye** [comment]
复现原因了 。。。   我前面使用的 pnpm 安装的依赖，大佬可以试一下使用 pnpm 看看能否还原出我的这种情况

**Comment by woai3c** [comment]
你这应该是缺少依赖了，换成 npm 试试看会有这个问题吗？

**Comment by woai3c** [comment]
在 npm 中，有时某个包作为间接依赖被自动解析为正常依赖。但是 pnpm 需要你在项目的 package.json 中明确列出所有实际使用的包，否则会提示缺少依赖。

**Comment by issueye** [comment]
在 npm 下确实是没有出现这样的问题了  感谢

**Comment by woai3c** [comment]
> 在 npm 下确实是没有出现这样的问题了 感谢

pnpm 也是可以正常运行的，前提是你把缺失的依赖补上。
