### ISSUE TITLE
Window系统启动报错：ESLint: error Delete `␍` prettier/prettier解决方案

### ISSUE THREAD

**Issue by yuji8023** [woai3c/visual-drag-demo#137]
> 该错误通常与行尾换行符相关。

### 一、行尾换行符问题

通常是由于不同操作系统之间的换行符差异引起的。

windows：在换行的时候同时使用了CR和LF换行符，即\r\n

Mac和Linux：仅仅使用了换行符LF，即\n

在使用 Git 等版本控制工具时，可能会出现行尾换行符混合的情况，从而导致 Prettier 报错。

### 二、解决方案

在`.eslintrc.js`中增加配置，忽略换行格式的检查
`'prettier/prettier': ['error', { endOfLine: 'auto' }],`

**Comment by woai3c** [comment]
> > 该错误通常与行尾换行符相关。
> 
> ### 一、行尾换行符问题
> 通常是由于不同操作系统之间的换行符差异引起的。
> 
> windows：在换行的时候同时使用了CR和LF换行符，即\r\n
> 
> Mac和Linux：仅仅使用了换行符LF，即\n
> 
> 在使用 Git 等版本控制工具时，可能会出现行尾换行符混合的情况，从而导致 Prettier 报错。
> 
> ### 二、解决方案
> 在`.eslintrc.js`中增加配置，忽略换行格式的检查 `'prettier/prettier': ['error', { endOfLine: 'auto' }],`

强制将所有文件的换行符设置为 `lf` 是有意为之的。我加了个配置，应该会自动的将 `crlf` 转换为 `lf`。https://github.com/woai3c/visual-drag-demo/commit/e839e68047c178f1ebcf964a0d4d0a3594cb781b
