### ISSUE TITLE
大佬，实现tabs组件的思路是什么？

### ISSUE THREAD

**Issue by yuji8023** [woai3c/visual-drag-demo#138]
![1727340879804](https://github.com/user-attachments/assets/c0429986-e5da-412d-ae05-1d2656c24d09)
类似tooljet那种的

**Comment by woai3c** [comment]
这种在使用绝对位移的布局里不好做。你这种情况比较合适那种支持嵌套渲染的，例如一个组件有支持子组件 children。你可以找一些开源的低代码表单，改一改就可以用了。这种都不是使用绝对位移来布局的。

**Comment by yuji8023** [comment]
这个卡了我一天了，真的没有办法了吗？只能放弃visual-drag-demo了吗

**Comment by woai3c** [comment]
> 这个卡了我一天了，真的没有办法了吗？只能放弃visual-drag-demo了吗

可以参考一下组合的实现方式，实现一个 tabs 布局，可以接受 children 递归渲染。是可以实现的，但是有一定难度。

**Comment by woai3c** [comment]
太久没响应了，关闭问题。

**Comment by Web-Li** [comment]
提供一个思路供你参考，假如我理解的对的话：你有ABC 三个组件，需要放在Tab1、Tab2、Tab3里面分别展示。
1、展示隐藏：我们知道Tabs主要就是做一个展示隐藏逻辑，且轮子里面是支持组件间联动的，我们以element的Tab为例，那么你可以在Tab组件上给具体的Tab点击绑定事件，同时给当点击Tab组件的Tab时，记录下当前具体的activeTab，另外在轮子联动的面板那里，与点击、hover并列增加一个Tab点击事件，同时把Tab组件的Tab枚举作为列表暴露出来，这样进行组件绑定的时候，在linkage里面就可以把具体的TabName存下来。这样在事件触发的时候，通过对关联组件的style进行操作，比如加上display属性，设置为none又或者空，就可以实现展示隐藏的功能。
2、拖拽跟随：可以对组件进行位置校验，当某个组件与tab绑定，并且它的四个关键坐标点都在content的目标区域，那么在拖拽tab组件的时候，把位移差同步给这些组件，你可以给Tab组件的content区域可以加上一个灰色底色，这样其他组件在拖拽过来的时候就有目标区了。
