### ISSUE TITLE
是否支持画布边界设置，画布内的组件不允许超过画布边界

### ISSUE THREAD

**Issue by ziyujiahao** [woai3c/visual-drag-demo#14]
是否支持画布边界设置，画布内的组件不允许超过画布边界

**Comment by woai3c** [comment]
给画布加一个 overflow: hidden 属性，超出边界自动隐藏。

**Comment by ziyujiahao** [comment]
这样的话 组件的边框还是能拖拽出去 只不过被隐藏了 能不能让组件边框不能越过画布边框

**Comment by woai3c** [comment]
> 这样的话 组件的边框还是能拖拽出去 只不过被隐藏了 能不能让组件边框不能越过画布边框

这个需要 mousemove 事件中判断组件的 top left width height 属性，并且和画布的边界做对比。目前不考虑加这个功能，建议你 fork 项目，自己加一下。

**Comment by ziyujiahao** [comment]
好的 多谢
