### ISSUE TITLE
组件拆分和组件赋值以及生成页面预览遇到的问题

### ISSUE THREAD

**Issue by zym0110** [woai3c/visual-drag-demo#15]
你好,作者大佬,首先感谢你贡献,让我免于开除....,最近在使用的时候发现几个问题
1.操作方式：拖动两个组件，选中后组合并复制，拆分第二次组合的组件，会消失，并在原组件上生成一个新的;
原因应该是拖动后的复制组件,被拆分后几个组件使用的是第一次的坐标
2.我在原有的组件基础上加了echart图表,如果echart给动态赋过数据后,那么执行撤回和重做的操作会使echart变成空白
原因应该是赋值的操作没有添加入快照中,需要将赋值这一步加入记录,但是我在赋值的时候加入了添加快照的方法,好像不生效
3.如果将画布大小设置为1920*1080,scale为60%,我将预览的页面大小设置为1920*1080,scale为100%,页面中组件会位置在左侧,那如果生成的大屏页面怎么做到完全贴合呢
大佬,我应该是个菜鸡了,这几个问题,我研究了两天,改了总是有bug,期望你的回复,谢谢,感谢大佬的贡献

**Comment by woai3c** [comment]
1. 第一个问题需要重新修改拆分逻辑才行，挺麻烦的。目前我刚换工作不久，有点忙，应该不会改这个逻辑。
2. 添加快照我用的深拷贝来复制数据，这个深拷贝考虑了对象和数组，应该是没问题的。建议你打断点一步步调试看看。
3. 画布设计的时候最好和最终要的效果一模一样，包括大小及比例。

**Comment by zym0110** [comment]
好的,多谢大佬
