### ISSUE TITLE
拖拽完组件,更改图纸比例属性, 如果把属性配置框内容删除了,再设置,导致之前的组件属性消失,拖动不了.

### ISSUE THREAD

**Issue by rolitter** [woai3c/visual-drag-demo#16]
![aaa](https://user-images.githubusercontent.com/27326998/114846858-aed7ac00-9e0f-11eb-99c0-f0867660d5a2.gif)

![image](https://user-images.githubusercontent.com/27326998/114846288-20fbc100-9e0f-11eb-8b0c-65f3db3e9880.png)

**Comment by woai3c** [comment]
好的，感谢反馈，等过几天有空了我看一下。

**Comment by woai3c** [comment]
已修复。
