### ISSUE TITLE
组合组件会将其他组件删除

### ISSUE THREAD

**Issue by zym0110** [woai3c/visual-drag-demo#19]
![微信截图_20210422201844](https://user-images.githubusercontent.com/48800373/115712978-0f369280-a3a8-11eb-84f2-e06eef1a7455.png)
我看这里面的组合方法有两个删除,会导致将两个组合组件再组合的时候,会无辜删除了其他组件

**Comment by woai3c** [comment]
> ![微信截图_20210422201844](https://user-images.githubusercontent.com/48800373/115712978-0f369280-a3a8-11eb-84f2-e06eef1a7455.png)
> 我看这里面的组合方法有两个删除,会导致将两个组合组件再组合的时候,会无辜删除了其他组件

两个组合的组件再组合就会变成一个组合组件，原来的两个组合组件会消失。

**Comment by zym0110** [comment]
![GIF 2021-4-23 9-14-51](https://user-images.githubusercontent.com/48800373/115803964-8b66bf80-a414-11eb-93f5-75b8560260dd.gif)
我知道应该删除原本的,但是现在好像不仅仅是删除了原本的,可能我考虑的不对,还请大佬见谅,不过你可以看下我在你的demo上录的屏

**Comment by woai3c** [comment]
> ![GIF 2021-4-23 9-14-51](https://user-images.githubusercontent.com/48800373/115803964-8b66bf80-a414-11eb-93f5-75b8560260dd.gif)
> 我知道应该删除原本的,但是现在好像不仅仅是删除了原本的,可能我考虑的不对,还请大佬见谅,不过你可以看下我在你的demo上录的屏

你最后删除的是整个组合吗，如果是的话，这是正常的。

**Comment by cubemoon** [comment]
如果要组合的组件中，已经存在组合数据，为什么要拆分呀，不能直接组合嵌套吗？
