### ISSUE TITLE
是否能支持光标移动到组件之后 鼠标能够显示十字

### ISSUE THREAD

**Issue by wangzhen1990** [woai3c/visual-drag-demo#2]

**Comment by woai3c** [comment]
鼠标的光标是可以自己设置的，看一下 [MDN 文档](https://developer.mozilla.org/zh-CN/docs/Web/CSS/cursor)。

**Comment by wangzhen1990** [comment]
当鼠标位于内容元素边框位置时候 鼠标变为十字 方便知道这个是可以拖动的

**Comment by woai3c** [comment]
> 当鼠标位于内容元素边框位置时候 鼠标变为十字 方便知道这个是可以拖动的

请参考 MDN 文档，自己设置。

**Comment by woai3c** [comment]
这不是一个正式的开源项目，仅仅是一个 DEMO。用于分析拖拽项目的原理。
