### ISSUE TITLE
关于键盘粘贴问题 

### ISSUE THREAD

**Issue by wyf521-sudo** [woai3c/visual-drag-demo#21]
我将此项目嵌套我当前项目中，只要打开工艺图页面，不做任何操作，然后关闭后，进入"其他页面"粘贴内容时一直提示‘请选择组件’，我怎么才能让这个粘贴事件不影响我这个"其他页面"呢

**Comment by woai3c** [comment]
可以在 APP 中加一个 destory 事件 当退出项目触发这个事件时取消监听按键事件。你可以看一下具体的监听函数，设成一个独立的函数，导出来，到时就能取消监听了。

**Comment by woai3c** [comment]
太久没有响应，关闭问题。

**Comment by wyf521-sudo** [comment]
之前加过destory 事件没啥用，关闭了拖拽组件库之后，对其他页面的复制粘贴事件还是有影响，可能有些时候这个拖拽组件库是在新的页面打开，其他页面还在，或者说我这个拖拽组件库是一个弹窗的形式，有一个关闭按钮，关闭后还是会影响。所以怎么才能让拖拽组件库页面的复制粘贴事件不影响我其他页面的复制粘贴事件呢

**Comment by woai3c** [comment]
> 之前加过destory 事件没啥用，关闭了拖拽组件库之后，对其他页面的复制粘贴事件还是有影响，可能有些时候这个拖拽组件库是在新的页面打开，其他页面还在，或者说我这个拖拽组件库是一个弹窗的形式，有一个关闭按钮，关闭后还是会影响。所以怎么才能让拖拽组件库页面的复制粘贴事件不影响我其他页面的复制粘贴事件呢

在点击关闭按钮的时候手动清除一下已经注册的事件。

**Comment by wyf521-sudo** [comment]
如何清除
![Uploading image.png…]()

**Comment by wyf521-sudo** [comment]
我复制的时候老提示‘请选择组件’
paste(state, isMouse) {
      if (!state.copyData) {
        toast('请选择组件')
        return
      }

      const data = state.copyData.data

      if (isMouse) {
        data.style.top = state.menuTop
        data.style.left = state.menuLeft
      } else {
        data.style.top += 10
        data.style.left += 10
      }

      data.id = generateID()
      store.commit('process/addComponent', { component: deepCopy(data) })
      if (state.isCut) {
        state.copyData = null
      }
    },

**Comment by wyf521-sudo** [comment]
这个跟// 全局监听按键事件
 listenGlobalKeyDown()   有关系吗

**Comment by wyf521-sudo** [comment]
我好像写出来了，谢谢大佬
