### ISSUE TITLE
组合功能的问题

### ISSUE THREAD

**Issue by cubemoon** [woai3c/visual-drag-demo#22]
如果要组合的组件中，已经存在组合数据，为什么要拆分呀，不能直接组合嵌套吗？

**Comment by woai3c** [comment]
目前只有一层组合，没有做嵌套组合。

**Comment by cubemoon** [comment]
> 目前只有一层组合，没有做嵌套组合。

试了下，去掉拆分代码，直接嵌套组合，运行起来没有什么问题
