### ISSUE TITLE
发生偏移

### ISSUE THREAD

**Issue by xiaofu39** [woai3c/visual-drag-demo#24]
![动画](https://user-images.githubusercontent.com/49585748/123750186-de636400-d8e8-11eb-9590-aeaa74f60c44.gif)

**Comment by woai3c** [comment]
你好，我这复现不了。你应该动过代码吧？

**Comment by xiaofu39** [comment]
没有改你的代码     我在我项目里加入了你那边的部分代码     我在元器件组件中加了一个padding的像素   应该是这个的原因

**Comment by xiaofu39** [comment]
> 你好，我这复现不了。你应该动过代码吧？

没有改你的代码 我在我项目里加入了你的部分代码 我在组件中加了一个填充像素应该是这个原因

**Comment by xiaofu39** [comment]
> 你好，我这复现不了。你应该动过代码吧？

没有改你的代码 我在我项目里加入了你的部分代码 我在组件中加了一个padding像素应该是这个原因

**Comment by woai3c** [comment]
> > 你好，我这复现不了。你应该动过代码吧？
> 
> 没有改你的代码 我在我项目里加入了你的部分代码 我在组件中加了一个padding像素应该是这个原因

先试试，看看效果。

**Comment by woai3c** [comment]
太久未响应，关闭。
