### ISSUE TITLE
shape每一条边的middle point 拉伸时产生偏移问题

### ISSUE THREAD

**Issue by justJokee** [woai3c/visual-drag-demo#26]
初始化如下图：

![23632A9AB3B0BA1DF0FB38BCD083078F](https://user-images.githubusercontent.com/35912907/124574078-b477e780-de7c-11eb-8dbe-3cb18984850c.jpg)

元素top初始值是175，如图所示bottom拖拽一下，按理来说top值应该始终为175不变，但是有时候会产生正负几个像素的偏差（如果一次没出现，就让元素失焦再选中，重复几次），经测试其它点均有此问题

![9C421EB84CA339ED4682AA3EE5975673](https://user-images.githubusercontent.com/35912907/124574275-e2f5c280-de7c-11eb-8469-8739799c0e41.jpg)

这样就会给人呈现元素突然位移抖一下的现象，是否各种矩阵计算导致了center值或者height值出现了偏差？

**Comment by justJokee** [comment]
晚上看了一下，是因为shape上的point点也是有尺寸的，直接用鼠标位置计算被拖动元素的点的position是不准确的，因为此时鼠标可能位于point点的任意位置，因此要计算差值，以确保点位于元素自身上，已提交pr

**Comment by HarryLee-CN** [comment]
嚯，非常细节，我试了一下确实可以复现

**Comment by ggymm** [comment]
> 晚上看了一下，是因为shape上的point点也是有尺寸的，直接用鼠标位置计算被拖动元素的点的position是不准确的，因为此时鼠标可能位于point点的任意位置，因此要计算差值，以确保点位于元素自身上，已提交pr

换种思路，边上的点是不是可以直接取50%，不按照元素大小去计算了呢
```javascript
{
  't': { name: 'top', style: { top: '-4px', left: '50%', marginLeft: '-4px', cursor: cursor.t, transform }},
  'rt': { name: 'top-right', style: { top: '-4px', right: '-4px', cursor: cursor.rt, transform }},
  'r': { name: 'right', style: { top: '50%', right: '-4px', marginTop: '-4px', cursor: cursor.r, transform }},
  'rb': { name: 'bottom-right', style: { right: '-4px', bottom: '-4px', cursor: cursor.rb, transform }},
  'b': { name: 'bottom', style: { left: '50%', bottom: '-4px', marginLeft: '-4px', cursor: cursor.b, transform }},
  'lb': { name: 'bottom-left', style: { left: '-4px', bottom: '-4px', cursor: cursor.lb, transform }},
  'l': { name: 'left', style: { top: '50%', left: '-4px', marginTop: '-4px', cursor: cursor.l, transform }},
  'lt': { name: 'top-left', style: { top: '-4px', left: '-4px', cursor: cursor.lt, transform }}
}
```

**Comment by woai3c** [comment]
https://github.com/woai3c/visual-drag-demo/pull/27
