### ISSUE TITLE
VText组件v-html失效的疑问

### ISSUE THREAD

**Issue by NameWjp** [woai3c/visual-drag-demo#30]
我VText组件中看到这样一句话
```js
this.element.propValue = e.target.innerHTML || '&nbsp;'
```
很容易理解，在用户清空文本的情况下保留一个空格，但是实际测试的过程中有一些异常，异常的步骤如下：
1. 拖拽一个 VText 组件，清空里面的内容。
2. 触发 blur 事件，之后双击 VText 组件（可以看到有一个空格，是正常情况）
3. 再次清空 VText 组件
4. 再次触发 blur 事件，之后双击 VText 组件，发现并没有空格

一句话总结就是连续清空两次 VText 组件，v-html 并不会渲染。 
解决的办法很简单，在 blur 的时候赋值一个新值，watch 传入的 element 变化，使用 innerHTML 手动赋值。  
但我比较好奇这里的 v-html 为什么会在连续清除两次后会失效，如果你知道原因，请告诉我，不胜感激。

**Comment by woai3c** [comment]
https://github.com/woai3c/visual-drag-demo/commit/b187f2b487f7e70e3d186f90a0df3655ed76c4e7
