### ISSUE TITLE
清空画布、撤销到画布上没有组件的时候，建议右侧边栏也清空！

### ISSUE THREAD

**Issue by herpaydrin** [woai3c/visual-drag-demo#39]
RT：
建议对 componentData 做监听

**Comment by woai3c** [comment]
@NameWjp 兄弟看看有没有空把这个也解决了。

**Comment by woai3c** [comment]
https://github.com/woai3c/visual-drag-demo/commit/755c8d22dd897a7aef6f13edd061cb436315a0fa
