### ISSUE TITLE
旋转之后拉伸会有抖动

### ISSUE THREAD

**Issue by lesley920719** [woai3c/visual-drag-demo#46]

**Comment by woai3c** [comment]
目前暂时没有解决方案，实现算法有问题。

**Comment by Blizzard-liu** [comment]
刚试了下  抖动的很明显

**Comment by AnsGoo** [comment]
这个bug我能解决可否提交合入

**Comment by Blizzard-liu** [comment]
牛啊   你是学算法的吗

**Comment by AnsGoo** [comment]
不是，我自己在项目中重写了这段算法。不抖动了

**Comment by woai3c** [comment]
> 这个bug我能解决可否提交合入

可以提个 issue，我合并一下.

**Comment by AnsGoo** [comment]
组件拉伸算法的主要思路是，

已知鼠标落脚点`p0`和组件的`top` 、`left` 、`height` 、`width` 以及`rotate`


1. 确定是哪个拉伸点`p1*`，并找到这个`p1*`点在组件上的中心对称点`p2*`,
3. 围绕组件中心点旋转`p2*`得到`p2`点，`p2`在为`p2*`笛卡尔坐标系中的坐标
4. 根据`p0`点和`p2`点计算拉伸之后的组件的新中心点`O2`
5. 围绕`O2`反向旋转`p0`点得到点`p0*`，点`p0*`为点`p0`在`css坐标系`中的坐标
6. 根据`p0*`算出对应场景下的组件坐标和长度

> 带\*点为直接css坐标系中的点表示方法，直接通过css的属性`top` 、`left` 、`height` 、`width` 可以得到，而不带\*的坐标是点在笛卡尔坐标系的坐标，需要考虑`rotate`

需要注意的是在拉伸`左`、`右`、`顶`、`底`四个点时鼠标的落脚点不是真实需要的落脚点！

> 以左拉伸为例，左拉伸只能将组件拉宽，这时候鼠标应该沿着过组件左、右点的直线L上移动，但是实际上坐标可以在任意区域移动，这时候需要根据直线L的方程式和鼠标落脚点(X，Y)中的X坐标，计算出落在直线上的Y`坐标，并以(X,Y`)作为真正的鼠标落脚点参与组件拉伸计算

**Comment by Blizzard-liu** [comment]
666

**Comment by woai3c** [comment]
> 组件拉伸算法的主要思路是，
> 
> 已知鼠标落脚点`p0`和组件的`top` 、`left` 、`height` 、`width` 以及`rotate`
> 
> 1. 确定是哪个拉伸点`p1*`，并找到这个`p1*`点在组件上的中心对称点`p2*`,
> 2. 围绕组件中心点旋转`p2*`得到`p2`点，`p2`在为`p2*`笛卡尔坐标系中的坐标
> 3. 根据`p0`点和`p2`点计算拉伸之后的组件的新中心点`O2`
> 4. 围绕`O2`反向旋转`p0`点得到点`p0*`，点`p0*`为点`p0`在`css坐标系`中的坐标
> 5. 根据`p0*`算出对应场景下的组件坐标和长度
> 
> > 带*点为直接css坐标系中的点表示方法，直接通过css的属性`top` 、`left` 、`height` 、`width` 可以得到，而不带*的坐标是点在笛卡尔坐标系的坐标，需要考虑`rotate`
> 
> 需要注意的是在拉伸`左`、`右`、`顶`、`底`四个点时鼠标的落脚点不是真实需要的落脚点！
> 
> > 以左拉伸为例，左拉伸只能将组件拉宽，这时候鼠标应该沿着过组件左、右点的直线L上移动，但是实际上坐标可以在任意区域移动，这时候需要根据直线L的方程式和鼠标落脚点(X，Y)中的X坐标，计算出落在直线上的Y`坐标，并以(X,Y`)作为真正的鼠标落脚点参与组件拉伸计算
![Mar-18-2022 16-26-54](https://user-images.githubusercontent.com/22117876/158964088-b6159f92-f927-4727-b36b-040d50ba83ac.gif)

你好，我看了一下你提的 PR，发现还是有抖动。

**Comment by AnsGoo** [comment]
当初决定替换这段算法的原因是我们遇到的抖动偶然性的十几，几十PX的跳动，还有就是旋转之后，组合之后组件的拉伸变成等比拉伸，而不是单方向上的拉伸，而旋转之后，各个方向上的拉伸都会导致（top,left)改变，而根据算法算出来的(top,left)是整数，因为精度丢失的问题，会有视觉上的颤动
![screenshots](https://user-images.githubusercontent.com/10111003/159024944-7b349caa-dd0a-4671-9a28-1a6b607b453a.gif)

**Comment by woai3c** [comment]
> 当初决定替换这段算法的原因是我们遇到的抖动偶然性的十几，几十PX的跳动，还有就是旋转之后，组合之后组件的拉伸变成等比拉伸，而不是单方向上的拉伸，而旋转之后，各个方向上的拉伸都会导致（top,left)改变，而根据算法算出来的(top,left)最后必须成整数，因为精度丢失的问题，会有视觉上的颤动 ![screenshots](https://user-images.githubusercontent.com/10111003/159024944-7b349caa-dd0a-4671-9a28-1a6b607b453a.gif)
> 
> 这个是我在我的项目中的实现的效果 ![screenshots](https://user-images.githubusercontent.com/10111003/159026278-37125ba2-260a-4f11-8bcf-585fed108f5f.gif)

原来如此，是否等比缩放主要看产品需求。虽然没有采纳你的 PR，但还是感谢你的反馈。
