### ISSUE TITLE
切换路由MarkLine.vue获取的$refs随着拖动一会有值一会没有值，元素拖动受到限制，

### ISSUE THREAD

**Issue by qwe104** [woai3c/visual-drag-demo#49]
![bg](https://user-images.githubusercontent.com/23718186/139526190-417ab618-03ed-4535-a170-c1dd59ad9669.png)

**Comment by qwe104** [comment]
![动画](https://user-images.githubusercontent.com/23718186/139527568-0e2ea9cf-8f0e-421b-8109-e6ef44c9de84.gif)

**Comment by woai3c** [comment]
复现操作步骤、复现代码是什么？DEMO 是没问题的。

**Comment by qwe104** [comment]
把空数组过滤掉后就不影响拖拽了，但是还不清楚拖动的过程中为什么$ref一会能获取到值,一会获取不到。
