### ISSUE TITLE
两处代码疑似有误

### ISSUE THREAD

**Issue by shaguo666** [woai3c/visual-drag-demo#50]
1. 图中红框两行代码是否重复
![image](https://user-images.githubusercontent.com/67275772/141035794-ade040da-66da-48af-acd0-a130bc1cc8e4.png)
2.Shape.vue里的getPointStyle(point)中mraginLeft三元表达式的判断两种结果都是-4px
![image](https://user-images.githubusercontent.com/67275772/141036076-94e6b659-ca63-4e27-b3a5-0ccfb6a43b98.png)

**Comment by woai3c** [comment]
https://github.com/woai3c/visual-drag-demo/commit/db6ba50ef5d8d2b7f80220c72a32ac1ee84b63df
