### ISSUE TITLE
动画列表里刚碰到动画时，动画会运行，但鼠标移开后，回到之前移入的动画，不会再产生动画

### ISSUE THREAD

**Issue by shaguo666** [woai3c/visual-drag-demo#51]
bug原因：在鼠标移出后hoverPreviewAnimate仍不变，即class中仍有动画类名
解决办法：可以同时加入鼠标移出事件，让hoverPreviewAnimate等于空字符串
![image](https://user-images.githubusercontent.com/67275772/141036916-85eee62b-0a31-4a79-8d81-030781f268d8.png)

**Comment by woai3c** [comment]
https://github.com/woai3c/visual-drag-demo/commit/f250cb47d5f94d5dd0f0252f4630bd9f91d3e1ba
