### ISSUE TITLE
当剪切某一组件后，再复制另一组件，剪切的组件会直接消失，而不是复原

### ISSUE THREAD

**Issue by shaguo666** [woai3c/visual-drag-demo#52]
解决办法：将cut方法里的还原剪切数据代码，同时加入到copy方法里
![image](https://user-images.githubusercontent.com/67275772/141037826-6da968a4-ea65-4466-af80-ab3fba7c5157.png)
![image](https://user-images.githubusercontent.com/67275772/141037742-b7103794-c3a0-45ba-bcda-3c1414e1691a.png)

**Comment by woai3c** [comment]
https://github.com/woai3c/visual-drag-demo/commit/402d7864753bb641db342549fe404b0123be6f4d
