### ISSUE TITLE
eventBus.$emit的move事件参数错误

### ISSUE THREAD

**Issue by shaguo666** [woai3c/visual-drag-demo#53]
Bug原因：move事件一直用最开始点击Shape的坐标作为比较坐标。举个例子：当我点击了Shape之后，在开始坐标的右边一直移动，无论是左移还是右移，当前鼠标坐标curX-startX会永远大于0，即move事件会认为，Shape在向右移动
![image](https://user-images.githubusercontent.com/67275772/141039258-fb6986a5-6b2e-4ac5-a8e5-1a0383e4ba36.png)
解决办法：move事件每次比较时，都应该用上一次鼠标移动的坐标作为比较坐标
![image](https://user-images.githubusercontent.com/67275772/141039382-2c6cbeaa-9f80-49f6-a3e5-a10e577ab639.png)

**Comment by woai3c** [comment]
这个功能是为了显示标线用的，假设 a b 两个组件，a 在左，b 在右。 从 a 的角度来看，不管你 b 怎么移动，只要是向 a 靠近，就是向左移动。
