### ISSUE TITLE
属性列表里，颜色选择器建议添加实时变化功能

### ISSUE THREAD

**Issue by shaguo666** [woai3c/visual-drag-demo#54]
原因：使用颜色选择器时，对应组件颜色也实时变化，看起来会更加直观
实现办法：颜色选择器自带active-change事件，可以用来获取面板实时颜色，并赋给组件
![image](https://user-images.githubusercontent.com/67275772/141042476-661067aa-d8ef-407f-ad50-aff0089d5d22.png)
![image](https://user-images.githubusercontent.com/67275772/141042538-6434ead0-204e-4363-950a-1b3e22c22d65.png)
![image](https://user-images.githubusercontent.com/67275772/141042569-d11d29e1-1bf5-4ad7-b88f-9055a44995e9.png)

**Comment by woai3c** [comment]
现在就是实时变化的。

**Comment by shaguo666** [comment]
我想说的是组件颜色能根据对应颜色选择器实时变化，像我图里这种情况，选择器颜色不断变化时，文字颜色却并没有改变
![1](https://user-images.githubusercontent.com/67275772/141074592-e709cda9-0aac-462d-af3a-280b722ddfab.gif)

**Comment by shaguo666** [comment]
> 现在就是实时变化的。

我想说的是组件颜色能根据对应颜色选择器实时变化，像我图里这种情况，选择器颜色不断变化时，文字颜色却并没有改变
![1](https://user-images.githubusercontent.com/67275772/141075056-ea100c0e-9291-4429-b745-ad51b47ab882.gif)

**Comment by woai3c** [comment]
> > 现在就是实时变化的。
> 
> 我想说的是组件颜色能根据对应颜色选择器实时变化，像我图里这种情况，选择器颜色不断变化时，文字颜色却并没有改变 ![1](https://user-images.githubusercontent.com/67275772/141075056-ea100c0e-9291-4429-b745-ad51b47ab882.gif)

了解了，不过这个功能我觉得不是很有必要，暂时不考虑添加。

**Comment by wangqinyu** [comment]
该功能有很大用处，建议增加
