### ISSUE TITLE
点击Shape的圆点时，光标是只是根据范围返回的，所以光标方向会与实际光标方向会有误差

### ISSUE THREAD

**Issue by shaguo666** [woai3c/visual-drag-demo#55]
![image](https://user-images.githubusercontent.com/67275772/141229726-d78922de-9a1a-4bc6-9562-f20d89d23fea.png)
![动画](https://user-images.githubusercontent.com/67275772/141228216-08c95d60-7edc-43a5-b22b-bed61ec1f4c4.gif)
强迫症看起来比较难受

**Comment by woai3c** [comment]
这个没有好的解决方案。

**Comment by shaguo666** [comment]
> 这个没有好的解决方案。

能否像圆点那样，搞8个光标，点到哪个圆点就出现哪个光标，每个光标用同一个png图片，不同的是需要给一个初始旋转角度，鼠标自带的光标在鼠标按下时就给它取消显示，弹起时再显示回来。
如果组件旋转，把旋转角度同时加上8个光标初始角度即可实现同向

**Comment by woai3c** [comment]
> > 这个没有好的解决方案。
> 
> 能否像圆点那样，搞8个光标，点到哪个圆点就出现哪个光标，每个光标用同一个png图片，不同的是需要给一个初始旋转角度，鼠标自带的光标在鼠标按下时就给它取消显示，弹起时再显示回来。 如果组件旋转，把旋转角度同时加上8个光标初始角度即可实现同向

这个方法不错，你可以 fork 一下项目，提个 pr.

**Comment by shaguo666** [comment]
> > > 这个没有好的解决方案。
> > 
> > 
> > 能否像圆点那样，搞8个光标，点到哪个圆点就出现哪个光标，每个光标用同一个png图片，不同的是需要给一个初始旋转角度，鼠标自带的光标在鼠标按下时就给它取消显示，弹起时再显示回来。 如果组件旋转，把旋转角度同时加上8个光标初始角度即可实现同向
> 
> 这个方法不错，你可以 fork 一下项目，提个 pr.

大佬，我刚刚试了下，我这方法其实根本不用给光标角度再添加旋转角度，它会自动跟着组件旋转，而且代码和圆点的代码十分类似，不同的是多了一个旋转角度。
![image](https://user-images.githubusercontent.com/67275772/141945223-fdc22320-3018-4199-8415-7092c389fec8.png)
![image](https://user-images.githubusercontent.com/67275772/141945332-e015f9a6-e6b7-4696-a724-ca3b1b30fd3e.png)
下面的红框的代码是我加的，里面比较重要的就是那个求旋转角度
![image](https://user-images.githubusercontent.com/67275772/141945599-f016172b-4b28-43f9-b8d4-2142cf5fdfb4.png)
我的大体思路是，根据组件的宽高，(1/2 * height)/(1/2 * width)=tanA，然后A=arctan（height/width），Math里的atan就是这个，不过算出来的是弧度，所以要做转换，这样得到的角度就可以直接放在rotate里了。
![image](https://user-images.githubusercontent.com/67275772/141946348-7f7551fb-a3ed-42c1-8370-d3a3a2aa4d43.png)
最终实现的效果是这样的，拉伸的时候角度也会变，旋转的时候角度不用变。
![3](https://user-images.githubusercontent.com/67275772/141947512-9b9b042c-913c-4e3e-8c1a-04ad4417e452.gif)
但是大佬，我觉得还是您来添加这些代码比较好，因为我感觉我写的代码有点重复，没那么优雅

**Comment by woai3c** [comment]
> > > > 这个没有好的解决方案。
> > > 
> > > 
> > > 能否像圆点那样，搞8个光标，点到哪个圆点就出现哪个光标，每个光标用同一个png图片，不同的是需要给一个初始旋转角度，鼠标自带的光标在鼠标按下时就给它取消显示，弹起时再显示回来。 如果组件旋转，把旋转角度同时加上8个光标初始角度即可实现同向
> > 
> > 
> > 这个方法不错，你可以 fork 一下项目，提个 pr.
> 
> 大佬，我刚刚试了下，我这方法其实根本不用给光标角度再添加旋转角度，它会自动跟着组件旋转，而且代码和圆点的代码十分类似，不同的是多了一个旋转角度。 ![image](https://user-images.githubusercontent.com/67275772/141945223-fdc22320-3018-4199-8415-7092c389fec8.png) ![image](https://user-images.githubusercontent.com/67275772/141945332-e015f9a6-e6b7-4696-a724-ca3b1b30fd3e.png) 下面的红框的代码是我加的，里面比较重要的就是那个求旋转角度 ![image](https://user-images.githubusercontent.com/67275772/141945599-f016172b-4b28-43f9-b8d4-2142cf5fdfb4.png) 我的大体思路是，根据组件的宽高，(1/2 * height)/(1/2 * width)=tanA，然后A=arctan（height/width），Math里的atan就是这个，不过算出来的是弧度，所以要做转换，这样得到的角度就可以直接放在rotate里了。 ![image](https://user-images.githubusercontent.com/67275772/141946348-7f7551fb-a3ed-42c1-8370-d3a3a2aa4d43.png) 最终实现的效果是这样的，拉伸的时候角度也会变，旋转的时候角度不用变。 ![3](https://user-images.githubusercontent.com/67275772/141947512-9b9b042c-913c-4e3e-8c1a-04ad4417e452.gif) 但是大佬，我觉得还是您来添加这些代码比较好，因为我感觉我写的代码有点重复，没那么优雅

没事，你可以提一版，我再优化，或者我周末再看看。

**Comment by shaguo666** [comment]
> 
> 没事，你可以提一版，我再优化，或者我周末再看看。

那还是等大佬您有空再弄( • ̀ω•́ )✧

**Comment by woai3c** [comment]
刚试了一下，cursor 使用的光标图片不会随着元素角度旋转而旋转，所以这个方法行不通。

**Comment by shaguo666** [comment]
> 刚试了一下，cursor 使用的光标图片不会随着元素角度旋转而旋转，所以这个方法行不通。

光标图片？是说光标的div给一个背景图片吗？

**Comment by woai3c** [comment]
> > 刚试了一下，cursor 使用的光标图片不会随着元素角度旋转而旋转，所以这个方法行不通。
> 
> 光标图片？是说光标的div给一个背景图片吗？

对

**Comment by shaguo666** [comment]
> > > 刚试了一下，cursor 使用的光标图片不会随着元素角度旋转而旋转，所以这个方法行不通。
> > 
> > 
> > 光标图片？是说光标的div给一个背景图片吗？
> 
> 对
大佬，我试了下，这样给元素一个背景光标图片是可以一起旋转的
![image](https://user-images.githubusercontent.com/67275772/144777434-8c1ebf67-d14b-4954-9026-96aa7e9b1ea5.png)
![3](https://user-images.githubusercontent.com/67275772/144780537-0a4fc1c3-da11-42d1-97c9-1666f154fdbe.gif)

**Comment by woai3c** [comment]
> > > > 刚试了一下，cursor 使用的光标图片不会随着元素角度旋转而旋转，所以这个方法行不通。
> > > 
> > > 
> > > 光标图片？是说光标的div给一个背景图片吗？
> > 
> > 
> > 对
> > 大佬，我试了下，这样给元素一个背景光标图片是可以一起旋转的
> > ![image](https://user-images.githubusercontent.com/67275772/144777434-8c1ebf67-d14b-4954-9026-96aa7e9b1ea5.png)
> > ![3](https://user-images.githubusercontent.com/67275772/144780537-0a4fc1c3-da11-42d1-97c9-1666f154fdbe.gif)

这种实现方式和光标不一样，太丑了。

**Comment by shaguo666** [comment]
> > > > > 刚试了一下，cursor 使用的光标图片不会随着元素角度旋转而旋转，所以这个方法行不通。
> > > > 
> > > > 
> > > > 光标图片？是说光标的div给一个背景图片吗？
> > > 
> > > 
> > > 对
> > > 大佬，我试了下，这样给元素一个背景光标图片是可以一起旋转的
> > > ![image](https://user-images.githubusercontent.com/67275772/144777434-8c1ebf67-d14b-4954-9026-96aa7e9b1ea5.png)
> > > ![3](https://user-images.githubusercontent.com/67275772/144780537-0a4fc1c3-da11-42d1-97c9-1666f154fdbe.gif)
> 
> 这种实现方式和光标不一样，太丑了。

这只是个例子，我没找到和光标一模一样的图片，就用了这个，而且我现在是直接显示八个光标，也没做判断鼠标移到圆点上才显示光标，那样应该就不会丑了。我的逻辑是隐藏原生光标，用div带背景光标来显示。

**Comment by shaguo666** [comment]
> 这只是个例子，我没找到和光标一模一样的图片，就用了这个，而且我现在是直接显示八个光标，也没做判断鼠标移到圆点上才显示光标，那样应该就不会丑了。我的逻辑是隐藏原生光标，用div带背景光标来显示。
应该也可以直接img标签

**Comment by shaguo666** [comment]
> 这只是个例子，我没找到和光标一模一样的图片，就用了这个，而且我现在是直接显示八个光标，也没做判断鼠标移到圆点上才显示光标，那样应该就不会丑了。我的逻辑是隐藏原生光标，用div带背景光标来显示。

应该也可以直接img标签

**Comment by woai3c** [comment]
> > 这只是个例子，我没找到和光标一模一样的图片，就用了这个，而且我现在是直接显示八个光标，也没做判断鼠标移到圆点上才显示光标，那样应该就不会丑了。我的逻辑是隐藏原生光标，用div带背景光标来显示。
> 
> 应该也可以直接img标签

这样也会同时显示光标和原生光标。

**Comment by shaguo666** [comment]
> 这样也会同时显示光标和原生光标。

是的，但可以在在圆点被鼠标按下的时候用cursor:none隐藏，弹起再显示回来

**Comment by woai3c** [comment]
> > 这样也会同时显示光标和原生光标。
> 
> 是的，但可以在在圆点被鼠标按下或悬浮的时候用cursor:none隐藏，弹起再显示回来

我考虑了一下，暂时不打算添加这个功能，毕竟属于锦上添花。如果你有兴趣可以提个 pr。
