### ISSUE TITLE
希望添加一个动画播放之前隐藏元素的功能

### ISSUE THREAD

**Issue by xiaolele188** [woai3c/visual-drag-demo#56]

**Comment by woai3c** [comment]
我在掘金看了一下你的动图，但是我复现不了。你可以在本项目的 DEMO 里试一下，看看效果。

**Comment by huanganfree** [comment]
@woai3c 老哥，这个功能我想试试，想提个pr，贡献点代码，可以吗？

**Comment by woai3c** [comment]
> 
现在是这个问题复现不了，我试了一下各个动画效果，基本上没问题。

**Comment by woai3c** [comment]
> @woai3c 老哥，这个功能我想试试，想提个pr，贡献点代码，可以吗？

你可以看一下另一个 issue，可以提个 pr，里面有实现思路。

**Comment by huanganfree** [comment]
> > @woai3c 老哥，这个功能我想试试，想提个pr，贡献点代码，可以吗？
> 
> 你可以看一下另一个 issue，可以提个 pr，里面有实现思路。

哈哈，谢谢老哥的回复，我估计那位提问者的意思，是隐藏元素的时间可以自定义，或者时间可以稍长些。这里面可以做些优化点。不知道我理解的对不对

**Comment by huanganfree** [comment]
实不相瞒，老哥，我在掘金和GitHub都关注你了，很厉害的一个人。

**Comment by huanganfree** [comment]
@woai3c  其实可以将动画这一功能点里的动画时长，是否循环动画等做出配置项。由用户去自定义。这样，进一步丰富demo的功能。

**Comment by woai3c** [comment]
> @woai3c 其实可以将动画这一功能点里的动画时长，是否循环动画等做出配置项。由用户去自定义。这样，进一步丰富demo的功能。

这个建议不错，你可以贡献个 pr。

**Comment by huanganfree** [comment]
> > @woai3c 其实可以将动画这一功能点里的动画时长，是否循环动画等做出配置项。由用户去自定义。这样，进一步丰富demo的功能。
> 
> 这个建议不错，你可以贡献个 pr。

好的，Thanks♪(･ω･)ﾉ
