### ISSUE TITLE
bug: 拖拽长方形创建两个组并保存，再新拖拽一个长方形加入其中一个组并组成新的组，保存后会另外一个组会消失

### ISSUE THREAD

**Issue by liaiwei** [woai3c/visual-drag-demo#58]

**Comment by woai3c** [comment]
感谢反馈，确实是个 bug，等有空了修复一下。

**Comment by woai3c** [comment]
@huanganfree  有空可以看看这个问题。

**Comment by huanganfree** [comment]
@woai3c 好的，有空我看看:accept:

**Comment by woai3c** [comment]
> _No description provided._

已修复 https://github.com/woai3c/visual-drag-demo/commit/cf1b0c4914be63825165520bdbe99100f30009ff
