### ISSUE TITLE
echarts拖拽组件

### ISSUE THREAD

**Issue by Grails125** [woai3c/visual-drag-demo#60]
增加echarts拖拽组件，修改宽高图表大小不变

**Comment by woai3c** [comment]
组件大小有没有跟着 shape 组件大小改变。

> 增加echarts拖拽组件，修改宽高图表大小不变

**Comment by Grails125** [comment]
> 组件大小有没有跟着 shape 组件大小改变。
> 
> > 增加echarts拖拽组件，修改宽高图表大小不变

没有呢，但是在预览时能看出来宽高的变化，只是组件大小还是初始大小

**Comment by woai3c** [comment]
> > 组件大小有没有跟着 shape 组件大小改变。
> > > 增加echarts拖拽组件，修改宽高图表大小不变
> 
> 没有呢，但是在预览时能看出来宽高的变化，只是组件大小还是初始大小

canvas 宽高都设成 100%.

**Comment by Grails125** [comment]
> > > 组件大小有没有跟着 shape 组件大小改变。
> > > > 增加echarts拖拽组件，修改宽高图表大小不变
> > 
> > 
> > 没有呢，但是在预览时能看出来宽高的变化，只是组件大小还是初始大小
> 
> canvas 宽高都设成 100%.

echarts组件内设置的宽高是100%，拖拽时传了宽高默认值，修改图表宽高还是没变化

**Comment by woai3c** [comment]
> > > > 组件大小有没有跟着 shape 组件大小改变。
> > > > > 增加echarts拖拽组件，修改宽高图表大小不变
> > > 
> > > 
> > > 没有呢，但是在预览时能看出来宽高的变化，只是组件大小还是初始大小
> > 
> > 
> > canvas 宽高都设成 100%.
> 
> echarts组件内设置的宽高是100%，拖拽时传了宽高默认值，修改图表宽高还是没变化

那你得看样式有没有生效。

**Comment by Grails125** [comment]
> > > > > 组件大小有没有跟着 shape 组件大小改变。
> > > > > > 增加echarts拖拽组件，修改宽高图表大小不变
> > > > 
> > > > 
> > > > 没有呢，但是在预览时能看出来宽高的变化，只是组件大小还是初始大小
> > > 
> > > 
> > > canvas 宽高都设成 100%.
> > 
> > 
> > echarts组件内设置的宽高是100%，拖拽时传了宽高默认值，修改图表宽高还是没变化
> 
> 那你得看样式有没有生效。

**Comment by Grails125** [comment]
> > > > > 组件大小有没有跟着 shape 组件大小改变。
> > > > > > 增加echarts拖拽组件，修改宽高图表大小不变
> > > > 
> > > > 
> > > > 没有呢，但是在预览时能看出来宽高的变化，只是组件大小还是初始大小
> > > 
> > > 
> > > canvas 宽高都设成 100%.
> > 
> > 
> > echarts组件内设置的宽高是100%，拖拽时传了宽高默认值，修改图表宽高还是没变化
> 
> 那你得看样式有没有生效。

嗯，试了改变窗口大小时，echarts大小才随shape改变一次

**Comment by woai3c** [comment]
> > > > > > 组件大小有没有跟着 shape 组件大小改变。
> > > > > > > 增加echarts拖拽组件，修改宽高图表大小不变
> > > > > 
> > > > > 
> > > > > 没有呢，但是在预览时能看出来宽高的变化，只是组件大小还是初始大小
> > > > 
> > > > 
> > > > canvas 宽高都设成 100%.
> > > 
> > > 
> > > echarts组件内设置的宽高是100%，拖拽时传了宽高默认值，修改图表宽高还是没变化
> > 
> > 
> > 那你得看样式有没有生效。
> 
> 嗯，试了改变窗口大小时，echarts大小才随shape改变一次

那可能是响应式数据没生效。
