### ISSUE TITLE
拿到数据后， 点击组件会出现如下情况

### ISSUE THREAD

**Issue by linwenfeng122** [woai3c/visual-drag-demo#62]
![bug](https://user-images.githubusercontent.com/19618653/153522121-31cbd686-dbbe-4b7d-9511-929215fcb66f.gif)
![image](https://user-images.githubusercontent.com/19618653/153522228-19e241e7-be0c-4581-b0d0-89818b842c21.png)

**Comment by linwenfeng122** [comment]
有时候就会出现这种，出现还挺高的

**Comment by linwenfeng122** [comment]
> > 有时候就会出现这种，出现还挺高的
> 
> 你用的这个版本是最新的源码吗？我用现在的在线 demo 试了一下复现不了，你在 demo 上试试看。

是最新的，但是demo 我也测不出来，就是不知道什么情况下会这样

**Comment by woai3c** [comment]
> > > > 有时候就会出现这种，出现还挺高的
> > > 
> > > 
> > > 你用的这个版本是最新的源码吗？我用现在的在线 demo 试了一下复现不了，你在 demo 上试试看。
> > 
> > 
> > 是最新的，但是demo 我也测不出来，就是不知道什么情况下会这样
> > 而且是有时候会，有时候不会这种情况

你改源码了吗？这种情况是因为当前组件为 null，然后去读取 null 的  styles 属性报错造成的。

**Comment by linwenfeng122** [comment]
> > > > 有时候就会出现这种，出现还挺高的
> > > 
> > > 
> > > 你用的这个版本是最新的源码吗？我用现在的在线 demo 试了一下复现不了，你在 demo 上试试看。
> > 
> > 
> > 是最新的，但是demo 我也测不出来，就是不知道什么情况下会这样
> > 而且是有时候会，有时候不会这种情况



> 

我知道原因了，可以关闭了，就是赋值先后出现问题

**Comment by woai3c** [comment]
> > > > > 有时候就会出现这种，出现还挺高的
> > > > 
> > > > 
> > > > 你用的这个版本是最新的源码吗？我用现在的在线 demo 试了一下复现不了，你在 demo 上试试看。
> > > 
> > > 
> > > 是最新的，但是demo 我也测不出来，就是不知道什么情况下会这样
> > > 而且是有时候会，有时候不会这种情况
> 
> > 
> 
> 我知道原因了，可以关闭了，就是赋值先后出现问题

ok
