### ISSUE TITLE
两个预览动画效果不一样

### ISSUE THREAD

**Issue by Blizzard-liu** [woai3c/visual-drag-demo#64]
![image](https://user-images.githubusercontent.com/20244432/156089098-a5f68ea5-e2dd-4667-a6ae-1eb873d6c476.png)

**Comment by woai3c** [comment]
请放上对比动图。

**Comment by Blizzard-liu** [comment]
![动画](https://user-images.githubusercontent.com/20244432/156093046-3a78f2ef-3fb7-40ee-8f42-4291ae63e6f3.gif)
一个是原地旋转  一个是旋转进入   两个预览的效果是不是不同

**Comment by Blizzard-liu** [comment]
大佬  这个更明显一点  
![动画1](https://user-images.githubusercontent.com/20244432/156094512-2bbf88e1-8494-427f-83b3-15cf6cbc125f.gif)

**Comment by woai3c** [comment]
感谢反馈，后续修复。

**Comment by woai3c** [comment]
已修复 https://github.com/woai3c/visual-drag-demo/commit/7939a0f51e816205d4e0651a68d8934bb57b8747 .
