### ISSUE TITLE
调整字体大小   边框没有同步缩放

### ISSUE THREAD

**Issue by Blizzard-liu** [woai3c/visual-drag-demo#65]
![image](https://user-images.githubusercontent.com/20244432/156089467-05b25ab6-7b19-4baa-a87f-7eb78399873a.png)

**Comment by woai3c** [comment]
需要手动修改文字后才会调整边框大小。

**Comment by Blizzard-liu** [comment]
![动画3](https://user-images.githubusercontent.com/20244432/156099168-68e33038-2c18-4e57-84cf-43ee8bdf9010.gif)
大佬  手动修改文字后边框也没调整

**Comment by woai3c** [comment]
> ![动画3](https://user-images.githubusercontent.com/20244432/156099168-68e33038-2c18-4e57-84cf-43ee8bdf9010.gif) 大佬 手动修改文字后边框也没调整

按下回车
