### ISSUE TITLE
内容输入框用键盘粘贴复制的文字   提示要选择组件

### ISSUE THREAD

**Issue by Blizzard-liu** [woai3c/visual-drag-demo#66]
![动画2](https://user-images.githubusercontent.com/20244432/156098235-2ecae4b1-f4af-401d-aedf-4aa6cb64e9d0.gif)
内容输入框用键盘粘贴复制的文字   提示要选择组件

**Comment by woai3c** [comment]
> 

刚试了一下，没有复现，你是不是改过源码？

**Comment by Blizzard-liu** [comment]
没改  我用的是神舟笔记本

**Comment by woai3c** [comment]
换了浏览器试了一下，没复现。你换个电脑试试。

**Comment by Blizzard-liu** [comment]
![动画4](https://user-images.githubusercontent.com/20244432/156280272-d9ffa7c3-a84b-41c0-b432-ece36dd44c2f.gif)
![image](https://user-images.githubusercontent.com/20244432/156280298-d5aee700-3f69-4e74-9ae0-e8b9433f531f.png)
这代码不是全局监听的吗   应该只在画布获取焦点的时候监听键盘操作

**Comment by Blizzard-liu** [comment]
https://github.com/phynos/WebTopo  这个项目复制粘贴就没问题

预览地址：http://42.192.126.212/WebTopo/dist/spa/

**Comment by Blizzard-liu** [comment]
@keydown.ctrl.67.stop="copyItem"
            @keydown.ctrl.86.stop="pasteItem"
            @keydown.ctrl.90.stop="undo"
            @keydown.ctrl.89.stop="redo"
            
            
            我觉得键盘监听操作应该放在组件上   不能通过window.onkeydown 全局监听

**Comment by woai3c** [comment]
已修复 https://github.com/woai3c/visual-drag-demo/commit/5eb11472cd31cd4a24f6bda581485469a7472c01
