### ISSUE TITLE
大佬  这个库怎么添加数据绑定  发布后就跟网页一样

### ISSUE THREAD

**Issue by Blizzard-liu** [woai3c/visual-drag-demo#68]

**Comment by woai3c** [comment]
没懂你的意思，请详细描述一下你的问题

**Comment by Blizzard-liu** [comment]
类似这样 添加数据源  https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.0/build/index.html

**Comment by Blizzard-liu** [comment]
![image](https://user-images.githubusercontent.com/20244432/157392988-4a6f7cf8-b0ea-45e5-ae4a-8c11c184b8a0.png)

**Comment by woai3c** [comment]
这个项目是个纯前端项目，没有涉及到后端和接口。所以不支持这个功能。
