### ISSUE TITLE
设计页面，坐标的手动输入被拦截，无法输入数字，可解决下，谢谢

### ISSUE THREAD

**Issue by yingfengchen** [woai3c/visual-drag-demo#69]
![image](https://user-images.githubusercontent.com/20177121/158316126-1a8f8f80-f305-43ff-b2b4-7e8dacb04a56.png)

**Comment by woai3c** [comment]
无法复现，请提供一个 GIF 看下复现过程。

**Comment by woai3c** [comment]
太久没响应，关闭问题。
