### ISSUE TITLE
当画布比例等于50%或者等于200%时,点击组件point改变矩形大小无效

### ISSUE THREAD

**Issue by vanche-phe** [woai3c/visual-drag-demo#74]
当画布比例等于50%或者等于200%时,点击组件point改变矩形大小无效

**Comment by woai3c** [comment]
我用 demo 试了一下，没有复现这个问题。可以描述一下复现步骤吗？

**Comment by vanche-phe** [comment]
> 
您先用画布大小50%模式改变下矩形组件大小,然后把画布大小改成200%，再改变矩形组件应该是改不了了，您先试下，如果不成功了我录个gif

**Comment by vanche-phe** [comment]
![動畫](https://user-images.githubusercontent.com/28480807/167248539-5af15cbb-843d-4023-b0f1-b05a849c6edb.gif)

**Comment by woai3c** [comment]
感谢反馈，已修复 https://github.com/woai3c/visual-drag-demo/commit/dbfeb52678a700cbdda394a98d0b12288bc01823
