### ISSUE TITLE
能否示例一下，怎样定义直线，曲线的组件，谢谢

### ISSUE THREAD

**Issue by zhc10130** [woai3c/visual-drag-demo#76]

**Comment by telee9527** [comment]
曲线这些需要Canvas绘制，可以看看这三个
https://github.com/konvajs/konva 
https://pixijs.com/
https://github.com/fabricjs/fabric.js

**Comment by woai3c** [comment]
可以看一下这个提交 https://github.com/woai3c/visual-drag-demo/commit/992a065051ef90d995b4d889654b2fe78212b9c2，我最近加了直线和一些 SVG 组件。
