### ISSUE TITLE
镜像翻转功能能否提供一个思路呢？

### ISSUE THREAD

**Issue by 18223781723** [woai3c/visual-drag-demo#78]
想实现类似ps变换控件那种功能，支持镜像翻转的旋转拉伸拖拽。

**Comment by woai3c** [comment]
镜像翻转是什么功能

**Comment by 18223781723** [comment]
我用的ps里面的变换控件做的演示。我想实现镜像翻转的功能。
![GIF 2022-6-12 21-26-39](https://user-images.githubusercontent.com/46308509/173235495-9bc74fda-9d66-4958-97d6-8a15ef809945.gif)

**Comment by 18223781723** [comment]
https://www.photopea.com/
在线版ps，他虽然用的是canvas实现的。但我想js操作dom理论上也是可行的。只不过我没有思路

**Comment by woai3c** [comment]
> https://www.photopea.com/ 在线版ps，他虽然用的是canvas实现的。但我想js操作dom理论上也是可行的。只不过我没有思路

可以把图片组件换成 canvas 实现，然后在拖拽翻转的时候把图片也翻一下。

**Comment by 18223781723** [comment]
就是翻转的时候搞不定呀

**Comment by woai3c** [comment]
> 就是翻转的时候搞不定呀

看看这个 https://www.zhangxinxu.com/study/201803/canvas-image-mirror.html

**Comment by woai3c** [comment]
已添加图片镜像翻转功能，https://github.com/woai3c/visual-drag-demo/commit/7b34a4fb7fbd2e9a168648b7f17c63eed11d76de .
