### ISSUE TITLE
home页面的resetId方法好像有点问题，如果组件是Group的话子组件没有重置id可能会导致id重复

### ISSUE THREAD

**Issue by zhc10130** [woai3c/visual-drag-demo#79]
home页面的resetId方法好像有点问题，如果组件是Group的话子组件没有重置id可能会导致id重复，同时需要遍历子组件重置id

**Comment by woai3c** [comment]
好的 我看一下

**Comment by woai3c** [comment]
已修复，感谢反馈 https://github.com/woai3c/visual-drag-demo/commit/75134f4d5490c744d25f0a6e9e7b5e1356174356
