### ISSUE TITLE
本项目的画布比例调整是通过style计算大小来调整的，计算后再恢复有问题

### ISSUE THREAD

**Issue by ZhangChuanyu123** [woai3c/visual-drag-demo#84]
可通过css的缩放来调整大小使之好用
editor.style.transform = 'scale('+val+')'; // 设置缩放比例

**Comment by woai3c** [comment]
不错，感谢反馈。

**Comment by woai3c** [comment]
刚试了下 scale，有不少问题。不知道你说的计算比例再恢复有问题是哪方面的问题。最好提供个能复现的动图。

**Comment by woai3c** [comment]
太久没响应，关闭问题
