### ISSUE TITLE
getBoundingClientRect() 返回的位置信息有很大概率存在多位的小数，影响用户体验

### ISSUE THREAD

**Issue by mishe** [woai3c/visual-drag-demo#85]
handleDrop(e) {
      e.preventDefault()
      e.stopPropagation()
      const index = e.dataTransfer.getData('index')
      const rectInfo = this.editor.getBoundingClientRect()
      // console.log(rectInfo)
      if (index) {
        const component = deepCopy(componentList[index])
        component.style.top = e.clientY - **Math.floor(rectInfo.y)**
        component.style.left = e.clientX - **Math.floor(rectInfo.x)**
        component.id = generateID()
        this.$store.commit('addComponent', { component })
        this.$store.commit('recordSnapshot')
      }
    }

建议增加加粗代码

**Comment by woai3c** [comment]
https://github.com/woai3c/visual-drag-demo/commit/2c396d11fa3296feeed46b0482971566db1653c0
