### ISSUE TITLE
文本组件的问题

### ISSUE THREAD

**Issue by liujianyu0126** [woai3c/visual-drag-demo#90]
![image](https://user-images.githubusercontent.com/112455330/187347947-04b973e9-4cb3-4db3-9c0a-c209e9d70447.png)
如图所示，我先点击文本组件进入编辑模式，在直接点击按钮组件，就能复现问题，并没有触发blur事件并且选中组件的事件也会出现问题

**Comment by woai3c** [comment]
感谢反馈，确实有这问题，晚点我看看。

**Comment by woai3c** [comment]
已修复 https://github.com/woai3c/visual-drag-demo/commit/0f0256edb03ceee3997e4d658795dbd47ddf51f2

**Comment by xuxiaoman123** [comment]
是不是直接这样子也可以呢:contenteditable="canEdit && curComponent?.id === element.id"

**Comment by woai3c** [comment]
> 是不是直接这样子也可以呢:contenteditable="canEdit && curComponent?.id === element.id"

我还没试过 你可以尝试下 如果这个方案可行 可以提交个 pr
