### ISSUE TITLE
画布改变比例与拖拽元素问题

### ISSUE THREAD

**Issue by tonesCottage** [woai3c/visual-drag-demo#91]
当设计后改变比例，众多已有元素成比例改变，没有问题。
此时再做元素拖拽，是否应该进入画布时等比例缩小

**Comment by woai3c** [comment]
按理来说，应该是要等比例缩小的，晚点我修改一下。

**Comment by woai3c** [comment]
已修复 https://github.com/woai3c/visual-drag-demo/commit/efe209ac6dd0933004a7776ab0a47cbf845a2326.
