### ISSUE TITLE
有个疑惑点，画布上拖拽的数据是根据componentData变化的还是curComponent，没发现两者的关联之处，求指导 #36

### ISSUE THREAD

**Issue by qiyx2019** [woai3c/visual-drag-demo#93]

**Comment by qiyx2019** [comment]
setShapeStyle 这个方法是更新curComponent 字段的， 画布组建的渲染是componentData，所以在哪里把两者关联的

**Comment by woai3c** [comment]
> setShapeStyle 这个方法是更新curComponent 字段的， 画布组建的渲染是componentData，所以在哪里把两者关联的

curComponent 当前点击的组件 componentData 是一个数组，包含了画布上所有的组件数据。

**Comment by qiyx2019** [comment]
画布元素的拖拽实际上是把curComponent的style属性传给了shape吧

**Comment by woai3c** [comment]
> 画布元素的拖拽实际上是把curComponent的style属性传给了shape吧

是的

**Comment by qiyx2019** [comment]
但是我没在你的getShapeStyle里看到去把curComponent的style属性传给shape，就没理解这块是怎么传的，我目前在用react重写你这个版本

**Comment by woai3c** [comment]
> 

直接在源码中搜这个方法名就可以了，每个组件都用会这个方法设置样式。

**Comment by qiyx2019** [comment]
getShapeStyle这个方法并没有从store中去拿curComponent的style属性，所以这里就没懂你是怎么取的

**Comment by woai3c** [comment]
> getShapeStyle这个方法并没有从store中去拿curComponent的style属性，所以这里就没懂你是怎么取的

v-for 遍历 componentData 取的

**Comment by qiyx2019** [comment]
componentData 和 curComponent在哪里关联的呢？handleMouseDownOnShape方法你是去设置curComponent的属性了，但是componentData从头到位 我没发现他是怎么更新的
