### ISSUE TITLE
功能优化建议

### ISSUE THREAD

**Issue by xagpx** [woai3c/visual-drag-demo#94]
建议完善以下功能，或提供解决思路，谢谢
1、增加画布标尺；
2、增加预览、发布、优化画布缩放、左右布局缩放功能；
3、增加动画条件触发功能--增加规则配置功能，及数据绑定；
4、增加自定义事件，自定义数据绑定解析功能；

![image](https://user-images.githubusercontent.com/13012069/193884914-37f3904f-07bb-43fb-a055-a8cc81656d21.png)
![image](https://user-images.githubusercontent.com/13012069/193885090-2accc44f-1e60-4709-89d6-36bfd286ebaa.png)

**Comment by xagpx** [comment]
![Uploading image.png…]()
左侧布局参考

**Comment by yswang0927** [comment]
@xagpx  请问您发的截图是什么软件的？

**Comment by woai3c** [comment]
谢谢你的建议，目前工作太忙，暂时没有时间去思考如何实现。如果你后续实现了，欢迎你提 PR。再次感谢。
