### ISSUE TITLE
组合与拆分

### ISSUE THREAD

**Issue by moshweilei** [woai3c/visual-drag-demo#95]
拖2个按钮节点组合然后复制，此时得到2组按钮，分别拆分。
问题一：重合
问题二：
![图片](https://user-images.githubusercontent.com/56259875/195267259-6b31840e-7d60-4cbe-bc64-81ec92083601.png)

**Comment by woai3c** [comment]
是 bug，后续修复。

**Comment by woai3c** [comment]
已修复，感谢反馈。
