### ISSUE TITLE
右键层级问题

### ISSUE THREAD

**Issue by moshweilei** [woai3c/visual-drag-demo#96]
![图片](https://user-images.githubusercontent.com/56259875/195299604-836cd356-db1d-42bf-b86f-3439a0c5437a.png)
右键层级问题

**Comment by woai3c** [comment]
复现步骤说一下

**Comment by moshweilei** [comment]
就拉大旋转一下然后在中间位置右击

**Comment by woai3c** [comment]
试了一下没复现，可以录个动图吗
